[package]
name = "practices"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
thirtyfour = "0.35.0"
tokio = { version = "1.42.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

